### ISSUE TITLE
Opengl is deprecated in macOS 10.14

### ISSUE THREAD

**Issue by chenzi26** [dilevin/computer-graphics-bounding-volume-hierarchy#1]
I just cloned assignment 4 and compiled it. It generates 24 warnings like this: 

computer-graphics-bounding-volume-hierarchy/libigl/external/glfw/src/nsgl_context.m:39:26: warning: 'NSOpenGLContext' is
      deprecated: first deprecated in macOS 10.14 - Please use Metal or MetalKit. [-Wdeprecated-declarations]
        [NSOpenGLContext clearCurrentContext];

computer-graphics-bounding-volume-hierarchy/libigl/external/glfw/src/nsgl_context.m:56:44: warning: 
      'NSOpenGLContextParameterSwapInterval' is deprecated: first deprecated in macOS 10.14 [-Wdeprecated-declarations]
                              forParameter:NSOpenGLContextParameterSwapInterval];

computer-graphics-bounding-volume-hierarchy/libigl/external/glfw/src/nsgl_context.m:267:23: warning: 'NSOpenGLPFASamples' is
      deprecated: first deprecated in macOS 10.14 [-Wdeprecated-declarations]
            setAttrib(NSOpenGLPFASamples, fbconfig->samples);
...

How to fix this or we can just ignore these warnings.

**Comment by ACalza** [comment]
Ignore the messages. Deprecated means they will no longer support future updates of OpenGL. You're fine.
