### ISSUE TITLE
OpenGL not working on CDF

### ISSUE THREAD

**Issue by wangshangsam** [dilevin/computer-graphics-bounding-volume-hierarchy#10]
Hi,

As it was working yesterday, today the following error shows up:

libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
GLX: Failed to create context: BadMatch (invalid parameter attributes)The GLFW library is not initializedThe GLFW library is not initializedThe GLFW library is not initializedSegmentation fault

**Comment by rin-23** [comment]
Can you checkout a new copy of A4 into some other folder and try compile it.

**Comment by wangshangsam** [comment]
That was a runtime error, not a compilation error.

But as I just checked, it seems to be working again now. Something must happened in between.
