### ISSUE TITLE
Can we use an AABB tree with just the left child as the base case?

### ISSUE THREAD

**Issue by Kevinktv** [dilevin/computer-graphics-bounding-volume-hierarchy#102]
Hello!

So I was wondering whether we could use an AABB tree with just the left side filled in as the base case. 
For example, if u pass in objects[1, 2]  // Two objects passed in
Your tree would look like
     
<img width="51" alt="Screenshot 2024-10-05 at 1 55 02 PM" src="https://github.com/user-attachments/assets/99a42068-232e-4da7-bbe9-1299fa1879e7">

Instead of 
    A
   /. \
  1.  2

The reason is that handling the other way required many more edge case checks (For instance, in a 3 - 1 split, the left side has 3 objects whereas the right has 1. It is easier to create an AABB tree with just a left side and assign it to the root instead of directly assigning the object to the roots right side.) You would only need one base case instead of multiple. (i.e. if objects passed in has size 1, just assign it to the left tree.)

Essentially, I'm ensuring that each leaf object (Like a triangle and cloudpoint) has an AABB tree associated with it whose right side is empty. This makes recursive calls and stuff a lot easier to handle. This standardizes the tree throughout instead of having some AABB with both children at the leaf positions and just 1 child and null ptr in other cases.

Thanks!

**Comment by Zhecheng-Wang** [comment]
I am not sure if this will make tree construction easier. I feel like you would need to create leaf nodes at some higher nodes and hardcode the construction logic. This would also create 2 more nodes.

**Comment by Kevinktv** [comment]
Okay so just clarifying, the moment we see that you only have 1 object in either the left or right division, you assign it directly to the corresponding subtree?
I was having some segfaults with this approach (mainly caused due to edge conditions. That's why I changed it but I'll try changing it back)

**Comment by Zhecheng-Wang** [comment]
During tutorial I mentioned if there is only 1 object, assign it to the left tree. If 2, one left one right. wdym by "only have 1 object in either the left or right division"?

**Comment by Kevinktv** [comment]
Oh sorry, I made some errors in my previous implementation. I am now directly assigning the leaf child now. 

Thanks!
