### ISSUE TITLE
AABB ray intersect both subtree intersection case

### ISSUE THREAD

**Issue by Kushagra-Raghuvanshi** [dilevin/computer-graphics-bounding-volume-hierarchy#103]
What are we supposed to do when hit is found in both the left and the right subtrees? Which subtree's t and descendant do we take? 
do we take left one's since its pre-order traversal or do we take the one with lower t as we have done in the past in case of multiple intersections

**Comment by Zhecheng-Wang** [comment]
Take the one with lower t makes more sense.

**Comment by Kushagra-Raghuvanshi** [comment]
solved
