### ISSUE TITLE
Viewer not working on CDF

### ISSUE THREAD

**Issue by JeremySant** [dilevin/computer-graphics-bounding-volume-hierarchy#11]
When I run `./rays` on CDF my code works fine until it tires to visualize the AABB tree. This was happening every time I ran `./rays` and I just assumed it was because I hadn't finished implementing everything for `./rays` yet, but now that I have I am still getting this error:

```
igl::opengl::glfw::Viewer usage:
  [drag]  Rotate scene
  A,a     Toggle animation (tight draw loop)
  F,f     Toggle face based
  I,i     Toggle invert normals
  L,l     Toggle wireframe
  O,o     Toggle orthographic/perspective projection
  T,t     Toggle filled faces
  Z       Snap to canonical view
  [,]     Toggle between rotation control types (trackball, two-axis
          valuator with fixed up, 2D mode with no rotation))
  <,>     Toggle between models
  ;       Toggle vertex labels
  :       Toggle face labels
GLX: GLX version 1.3 is requiredThe GLFW library is not initializedThe GLFW library is not initializedThe GLFW library is not initializedSegmentation fault
```

**Comment by rin-23** [comment]
There was a similar problem encountered by another student.  It seems to be working for him now. 
Is it still broken for you?

**Comment by JeremySant** [comment]
@rin-23 It is still broken for me

**Comment by rin-23** [comment]
Can you try and download a new copy of the assignment to another folder and compile/run it.

**Comment by Mincelot** [comment]
This is still an issue for me, I'm using SSH to access CDF and got the exact same error, anyone got this working yet?

**Comment by dilevin** [comment]
Does the code work when you run it locally on a CDF machine (i.e with no ssh) ?

**Comment by JeremySant** [comment]
@dilevin Went to Behan to try and it did not work locally on a CDF machine. I even tried to checkout a new copy of the code. Everything but the viewer works so it doesn't really stop me from completing the assignment but I am sure we will need the viewer in future assignments. Has anyone else actually confirmed that the viewer worked on a CDF machine?

**Comment by dilevin** [comment]
This [issue](https://github.com/dilevin/computer-graphics-bounding-volume-hierarchy/issues/10) suggests that the code will run on some CDF machines. I am working with CDF to try and figure out why that is/which machines it is.  Currently they have stated that 
1. some servers only support low level GLX extensions 
2. Different machines have different GPUs which could cause issues.

**Comment by arcady-genkin** [comment]
Hi, a teach.cs admin here. The error message "GLX: GLX version 1.3 is required" looks to me that you are running the code remotely. I know that, for example, the X server built into MacOS does not support GLX properly. Also, the X server provided by the NX server supports GLX up to verison 1.2, so this would not work in an NX session.

For anyone experiencing this, please do the following.
1. Try running the `glxgears` program just to make sure that the basic GL works for you. If it won't run, then you have an issue with your environment that you need to fix first.
2. If glxgears works, run the following commands and report the output:

```
hostname
glxinfo  |grep 'glx version'
```
