### ISSUE TITLE
./rays Issues in Viewing

### ISSUE THREAD

**Issue by Vesnushkin** [dilevin/computer-graphics-bounding-volume-hierarchy#110]
<img width="1142" alt="Screenshot 2024-10-07 at 1 24 12 AM" src="https://github.com/user-attachments/assets/ef35ac17-1640-4389-8f23-5b485018f580">

^ This is the result from running './rays ../data/rubber-ducky.obj'. I'm not sure where the issue lies specifically. Does anyone have any suggestions or experience with this issue?

**Comment by Zhecheng-Wang** [comment]
Box shape looks very off, I would say it's insert triangle into box or insert box into box that's buggy.

**Comment by Vesnushkin** [comment]
Update: Issue was found in AABBTree.
