### ISSUE TITLE
Find All Intersecting Pairs Base Case

### ISSUE THREAD

**Issue by grandrx10** [dilevin/computer-graphics-bounding-volume-hierarchy#111]
Hi, I am working with the find all intersecting pairs file and I am having some trouble writing the base case. If both subtrees are leaves, how do I know if they are intersecting? I can't use box box intersection because 2 triangles wouldn't necessarily be touching even if their boxes are intersecting. Is there something I'm missing?

![image](https://github.com/user-attachments/assets/008f234c-fb22-4de2-8866-ed4ed6be1181)

**Comment by milomg** [comment]
Find all intersecting box pairs

**Comment by Zhecheng-Wang** [comment]
This function is meant to find box box intersection pairs as the "broad phase". AABB is used to avoid computing every pair of triangle triangle intersection after all. We only computer triangle triangle intersection if their bounding box intersects.

**Comment by grandrx10** [comment]
OHHHH! Thanks very much.
