### ISSUE TITLE
Debugging problem 

### ISSUE THREAD

**Issue by Dryuont** [dilevin/computer-graphics-bounding-volume-hierarchy#117]
<img width="221" alt="Screenshot 2024-10-08 165746" src="https://github.com/user-attachments/assets/2b13480f-ea70-4667-9438-07639c77eb32">
I tried to run data\rubber-ducky.obj and got this. The brute force method is taking too long compared to the README file, and the use tree section is not showing.

**Comment by Zhecheng-Wang** [comment]
Compile in Debug mode to print out the stack trace with gdb.
