### ISSUE TITLE
LINK1104 error

### ISSUE THREAD

**Issue by jjackzhu** [dilevin/computer-graphics-bounding-volume-hierarchy#118]
I am also getting the same error shown in #106 
![Screenshot 2024-10-08 170241](https://github.com/user-attachments/assets/9f05cd7d-ad42-4a56-97c7-caa679d0023c)

I did a fresh install of the repo and I still get this error everytime I try to build the project.

**Comment by Zhecheng-Wang** [comment]
I would try the two solutions mentioned in this [StackOverflow](https://stackoverflow.com/questions/133698/why-does-fatal-error-lnk1104-cannot-open-file-c-program-obj-occur-when-i-c) post.

**Comment by jjackzhu** [comment]
I managed to successfully create the build by readding /Debug/ to the end of the output directory path in properties, and now I am getting this error in triangle_triangle_intersection and these warnings:

![Screenshot 2024-10-08 182440](https://github.com/user-attachments/assets/b8991d7a-2d0b-4280-867c-d1d147b0543f)
![Screenshot 2024-10-08 182808](https://github.com/user-attachments/assets/0998b98d-0944-4621-9146-cf3138c94f1a)
The error seems to go away when i comment out the two lines
Eigen::RowVector3d normal1 = (A1 - A0).cross(A2 - A0); and Eigen::RowVector3d normal1 = (B1 - B0).cross(B2 - B0);
I have tried adding #include <Eigen/LU> and #include <Eigen/Core> to the top of the file but nothing changes.

**Comment by Zhecheng-Wang** [comment]
Looking at the template Eigen<3,1>, it should a 3x1 matrix (so a 3D vector).
So when you cross Vector with Vector it returns Vector, not RowVector.

**Comment by Zhecheng-Wang** [comment]
Also did you include <Eigen/Dense>?

**Comment by jjackzhu** [comment]
thank you, that helped fix the error!
