### ISSUE TITLE
How to do triangle-triangle intersection?

### ISSUE THREAD

**Issue by wangshangsam** [dilevin/computer-graphics-bounding-volume-hierarchy#12]
Are we really gonna implement that famous algorithm (https://web.stanford.edu/class/cs277/resources/papers/Moller1997b.pdf)? Cuz it looks awfully complicated as a tiny part in a weekly assignment, and the point of this assignment is supposed to be BVH instead of primitive-primitive intersection testing.

**Comment by wangshangsam** [comment]
Even if we implement an not-so-efficient algorithm such that the brute force is 3 to 4 tines slower than the efficient one (however, the use-tree is still as efficient since not so many non-efficient primitive-primitive testing called in the first place)?

**Comment by rin-23** [comment]
yes thats fine
