### ISSUE TITLE
Part 2 Error (the one with TONS of points)

### ISSUE THREAD

**Issue by harrychy8** [dilevin/computer-graphics-bounding-volume-hierarchy#13]
I am having a problem where there are some extremely small errors in my calculation. I have tried to fix this bug for days but even after rewriting the entire part (like all of the functions), I couldn't fix it. Anyone else had similar issues that can help me?
![capture](https://user-images.githubusercontent.com/15678482/52321846-b041fa00-29a4-11e9-9124-398f011ac728.PNG)

**Comment by rarora7777** [comment]
It is possible that you're casting a `double` to a `float` somewhere?
