### ISSUE TITLE
Building AABB Tree splitting objects into left and right

### ISSUE THREAD

**Issue by jalowinner** [dilevin/computer-graphics-bounding-volume-hierarchy#15]
what if after we choose the longest axis one of the left/right part contains no object at all (all objects are on one side of the axis)?

**Comment by auderian** [comment]
I'm assuming you can set the relevant pointer (i.e. left or right) to `nullptr` to indicate to your code that there are no objects on that side

**Comment by ACalza** [comment]
Wouldn't that mean your leaf node is an AABB object rather than a regular object? I just pulled one object from one of the left/right to the other in order to satisfy all leaves are objects.

**Comment by rin-23** [comment]
This can happen when a single long triangle determines the bounds of the entire box and all objects go on one side. The "easiest" way to handle this is what @ACalza said. Pull one random object from one side and put it into the other.
