### ISSUE TITLE
Build tree takes long time for distance

### ISSUE THREAD

**Issue by Mincelot** [dilevin/computer-graphics-bounding-volume-hierarchy#16]
I'm quite confused about why this is the case because all the other programs build the tree in less than a second
# Ray Triangle Mesh Intersection
  |V| 2050
  |F| 4096

  Firing 1000 rays...

  | Method      | Time in seconds |
  |:------------|----------------:|
  | brute force |   0.54545593262 |
  | build tree  |   0.02316641808 |
  | use tree    |   0.00531315804 |

# Point Cloud Distance Queries
    |points|: 100000
  |querires|: 10000

  | Method      | Time in seconds |
  |:------------|----------------:|
  | brute force |   1.96922397614 |
  | build tree  |   7.21863555908 |
  | use tree    |   0.18951487541 |

# Triangle Mesh Intersection Detection
  |VA| 2002
  |FA| 4000

  |VB| 6669
  |FB| 13334

  | Method      | Time in seconds |
  |:------------|----------------:|
  | brute force |  75.28491282463 |
  | build trees |   0.17298388481 |
  | use trees   |   0.05544185638 |

What could be the reason or way to optimize building tree because I think there isn't much to optimize?

**Comment by rin-23** [comment]
Hard to say without looking at your code. 
Maybe you are doing some inefficient copying or extra loop.
