### ISSUE TITLE
Segmentation Fault occured in intersections.cpp

### ISSUE THREAD

**Issue by jwmaggiezhou** [dilevin/computer-graphics-bounding-volume-hierarchy#17]
![image](https://user-images.githubusercontent.com/21364786/52437140-21d49200-2ae4-11e9-974b-cb363dce6b9d.png)
it seems the `use tree` process has been completed, but I got a segmentationo fault afterwards in the comparison evaluation. What might be the potential problem with this error message? Thanks.

**Comment by rin-23** [comment]
you seem to be indexing one of the Eigen matrices for Faces or Verticies but the index is out of bound (larger than number of rows)

**Comment by jwmaggiezhou** [comment]
but weirdly, I didn't touch the MeshTriangle object and change its indexes throughout the program...

**Comment by rin-23** [comment]
try printing the indices when you access those matrices to see whats going on.

**Comment by jwmaggiezhou** [comment]
@disconcision  thanks for the reminder, but mine was even after `use tree` to find the leaf pairs, and it occurred in narrow phase when testing again with tri-tri intersection....will that still be the same issue?

**Comment by jwmaggiezhou** [comment]
@disconcision  thank you very much!!
