### ISSUE TITLE
Does use trees need to be faster than build trees?

### ISSUE THREAD

**Issue by Taryna** [dilevin/computer-graphics-bounding-volume-hierarchy#18]
My use trees takes longer than build trees for all 3 cases, while both are faster than brute force. Is that acceptable?

**Comment by rin-23** [comment]
I would say yes but can you post screenshot of your timings

**Comment by Taryna** [comment]
rays:
![rays](https://user-images.githubusercontent.com/5505167/52454362-7f370600-2b19-11e9-8f7c-889a3b801f10.png)

distances:
![distances](https://user-images.githubusercontent.com/5505167/52454394-9d046b00-2b19-11e9-8929-fc31a8a06ed1.png)

intersections:
![intersections](https://user-images.githubusercontent.com/5505167/52454412-b1486800-2b19-11e9-9767-c74632f46adb.png)

**Comment by rin-23** [comment]
I would expect that use tree should be faster than build tree, especially for distances. 
Are you sure you are running this in Release mode?

**Comment by Taryna** [comment]
Yes, I am. Any other suggestions?

**Comment by rin-23** [comment]
Hard to say without looking at your code. But the fact that it performs better than brute force is what really matters.

**Comment by Taryna** [comment]
Alright, thank you!
