### ISSUE TITLE
How to initialize pointers inside AABBTree? 

### ISSUE THREAD

**Issue by Geetchopra** [dilevin/computer-graphics-bounding-volume-hierarchy#19]
I am getting a "No viable overloaded "="" error when I try to initialize the left and right subtrees in the AABBTree function. How can I initialize them properly? 

I am using the definition as given in the assignment description (left = std::make_shared<Object>()).

Also, when I try to access the bounding box in the 'left' object, I get a segmentation fault. I hope someone can explain what I am doing wrong.

**Comment by rin-23** [comment]
I assume you are talking about AABBTree::AABBTree() consturctor function.

For example to create a left tree you can create a vector of pointers to Objects (call it left_objects for example)
Once you figure out which objects go to the left tree you add them to that vector.
Then you can create a new tree using make_shared:
left = std::make_shared<AABBTree>(left_objects , depth+1);

**Comment by Geetchopra** [comment]
I am still getting the segmentation fault. Any idea as to what I could be doing wrong? It is definitely because of accessing the left tree and its bounding box corners but I don't know how to fix it.
