### ISSUE TITLE
use of undeclared identifier

### ISSUE THREAD

**Issue by jishengx97** [dilevin/computer-graphics-bounding-volume-hierarchy#2]
I just cloned the repository and tried to compile, but it generated the following error:

[ 26%] Building C object glfw/src/CMakeFiles/glfw.dir/cocoa_window.m.o
/Users/jishengx/Documents/csc418/computer-graphics-bounding-volume-hierarchy/libigl/external/glfw/src/cocoa_window.m:446:40: error: use of undeclared identifier
      'NSPasteboardTypeFileURL'; did you mean 'NSPasteboardTypeRuler'?
                                       NSPasteboardTypeFileURL, nil]];
                                       ^~~~~~~~~~~~~~~~~~~~~~~
                                       NSPasteboardTypeRuler
/System/Library/Frameworks/AppKit.framework/Headers/NSPasteboard.h:31:31: note: 'NSPasteboardTypeRuler' declared here
APPKIT_EXTERN NSString *const NSPasteboardTypeRuler                     NS_AVAILABLE_MAC(10_6); // Replaces NSRulerPboardType
                              ^
/Users/jishengx/Documents/csc418/computer-graphics-bounding-volume-hierarchy/libigl/external/glfw/src/cocoa_window.m:735:54: error: use of undeclared identifier
      'NSPasteboardTypeFileURL'; did you mean 'NSPasteboardTypeRuler'?
    NSArray* files = [pasteboard propertyListForType:NSPasteboardTypeFileURL];
                                                     ^~~~~~~~~~~~~~~~~~~~~~~
                                                     NSPasteboardTypeRuler
/System/Library/Frameworks/AppKit.framework/Headers/NSPasteboard.h:31:31: note: 'NSPasteboardTypeRuler' declared here
APPKIT_EXTERN NSString *const NSPasteboardTypeRuler                     NS_AVAILABLE_MAC(10_6); // Replaces NSRulerPboardType
                              ^
2 errors generated.
make[2]: *** [glfw/src/CMakeFiles/glfw.dir/cocoa_window.m.o] Error 1
make[1]: *** [glfw/src/CMakeFiles/glfw.dir/all] Error 2
make: *** [all] Error 2

I'm on macOS 10.14.1. Any idea how I can fix this? Thanks in advance!

**Comment by rin-23** [comment]
Few things you should try:
1. update your Xcode
2. update/install command line tools
3. install any OS patches/security updates.
the restart your computer.

However, since the assignment depends on opegl (which is depreciated in OSX mojave) and glfw libraries we can't help you with compilation on any other platform besides CDF.  We tested that it runs and compiles on CDF. You can ssh to CDF or use NX client for remote access.
