### ISSUE TITLE
Display boxes for CloudPoints Task

### ISSUE THREAD

**Issue by jeremyxu1998** [dilevin/computer-graphics-bounding-volume-hierarchy#20]
Hi, I follow the pseudo code to write the distance function, the image displays and no errors detected. However, the Gif in the image folder shows lots of small boxes bounding a group of points, which make sense since this is what the task is. But my output image only contains the largest box as shown below. Which frame of the Gif image are we expecting for the image output? If I only have the largest box what could be the issue? Thanks!

![image](https://user-images.githubusercontent.com/39060475/52483326-9e697e00-2b81-11e9-95b0-a472283be7b3.png)

![image](https://user-images.githubusercontent.com/39060475/52483360-bb9e4c80-2b81-11e9-83c7-e93ec5026c58.png)

**Comment by dilevin** [comment]
You can use the , and . keys to view the tree at different depths (Decrease/Increase depth command shown at viewer start up). Here's what I get after pressing . 4 times:

<img width="812" alt="image" src="https://user-images.githubusercontent.com/1903521/52484008-4469b800-2b83-11e9-925d-cba19380ad34.png">

Reminder: You don't need to submit images. We will run your code to test it.

**Comment by jeremyxu1998** [comment]
This works for my program, thanks! But actually I am a bit curious what does that "depth" mean?

**Comment by dilevin** [comment]
depth, in this case, refers to how many levels you descend into the tree. It's the same depth as in depth-first traversal.

**Comment by jeremyxu1998** [comment]
That makes a lot of sense to me, thank you!
