### ISSUE TITLE
intersections brute force very slow

### ISSUE THREAD

**Issue by jalowinner** [dilevin/computer-graphics-bounding-volume-hierarchy#23]
When I run ./intersections it runs 831 seconds for the brute force but only 0.17 seconds for using tree.
Would it be a problem in my code or we can expect this situation to happen?

**Comment by rin-23** [comment]
13 mins is too slow

**Comment by auderian** [comment]
@rin-23 What about 49s?
@jalowinner make sure you're building in release configuration
`mkdir build_release
cd build_release
cmake -DCMAKE_BUILD_TYPE=Release ..
make `

**Comment by Kubik42** [comment]
Mine also takes a while (22). My guess is that it all depends on your triangle_triangle_intersect implementation.

**Comment by WyattLiu** [comment]
Maybe gprof is your friend, I got about 4s.
