### ISSUE TITLE
Why AABBTree ray intersect is log[n].

### ISSUE THREAD

**Issue by Meng-Wei** [dilevin/computer-graphics-bounding-volume-hierarchy#24]
Is it on average or even in the worst case? Cause I think we have to search until the leaf node to determine if we hit the child of current AABBTree given the provided data structure. Moreover, I don't know if I understand correctly: I thought we have to create a bounding box to contain all left or right objects, but there is no such field in the AABBTree. Do I misunderstand the concept of the BVH or AABB?

**Comment by disconcision** [comment]
average case; if the tree is well-balanced the depth will be order logn. there are fields for left and right subtrees, check the header file

**Comment by Meng-Wei** [comment]
> average case; if the tree is well-balanced the depth will be order logn. there are fields for left and right subtrees, check the header file

But I guess we have to traverse until the leaf node to determine if we hit left or right subtrees because we don't have bounding box covering subtrees. As I understand it, each AABBTree should have a bounding box which is used for the direct check. Please correct me if I am wrong.

**Comment by Meng-Wei** [comment]
I just noticed that AABBTree is a subclass of Object. I might need to re-write my ray-intersect.
