### ISSUE TITLE
Missing Eigen in CMake?

### ISSUE THREAD

**Issue by andriyDev** [dilevin/computer-graphics-bounding-volume-hierarchy#27]
In my implementation for ray_intersect_triangle.cpp (which I copied from A2 as recommended), I use computeInverseWithCheck. It seems though that the Eigen library isn't being linked, instead we are linking igl. But I guess igl never uses this function or something because when compiling I get an "unresolved external" for this function.

As an alternative I tried to compute the determinant (to check for bad inverse), and then use .inverse(), but some internal inverse class is also unresolved so it won't let me convert that to a Matrix3d.

In the CMakeLists.txt, they only include igl stuff:
`
add_library(core ${SRCFILES})
target_link_libraries(core igl::core igl::opengl igl::opengl_glfw )

add_executable(rays "rays.cpp")
target_link_libraries(rays core igl::core igl::opengl igl::opengl_glfw )

add_executable(distances "distances.cpp")
target_link_libraries(distances core igl::core igl::opengl igl::opengl_glfw )

add_executable(intersections "intersections.cpp")
target_link_libraries(intersections core igl::core igl::opengl igl::opengl_glfw )
`
Maybe this should include Eigen, and the repo should include eigen as a submodule? Or should I be calculating the ray/triangle intersect differently.

**Comment by rarora7777** [comment]
Include the Eigen LU module using
`#include <Eigen/LU>`

**Comment by andriyDev** [comment]
Thank you, this worked!
