### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by XQQGOODGIRL** [dilevin/computer-graphics-bounding-volume-hierarchy#3]
when I issue make, it shows:

libtool: unrecognized option `-c'
libtool: Try `libtool --help' for more information.
make[2]: *** [glfw/src/libglfw3.a] Error 1
make[1]: *** [glfw/src/CMakeFiles/glfw.dir/all] Error 2
make: *** [all] Error 2

I'm using mac, does anyone know how to solve it?

**Comment by rin-23** [comment]
Are you sure you have Xcode and Command Line Tools installed?
Check your OSX Updates page.

**Comment by XQQGOODGIRL** [comment]
yes I installed them

**Comment by rin-23** [comment]
can you post full output of running cmake and make commands

**Comment by XQQGOODGIRL** [comment]
build_release QiqiXu$ cmake -DCMAKE_BUILD_TYPE=Release ..
-- The C compiler identification is AppleClang 10.0.0.10001145
-- The CXX compiler identification is AppleClang 10.0.0.10001145
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found LIBIGL: /Users/QiqiXu/Downloads/third year courses/418/computer-graphics-bounding-volume-hierarchy/libigl/include  
-- Found libtool - /usr/local/bin/libtool
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE  
-- Creating target: igl::core (igl)
-- Creating target: igl::opengl (igl_opengl)
-- Found OpenGL: /System/Library/Frameworks/OpenGL.framework   
-- Creating target: igl::opengl_glfw (igl_opengl_glfw)
-- Could NOT find Vulkan (missing: VULKAN_LIBRARY VULKAN_INCLUDE_DIR) 
-- Using Cocoa for window creation
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/QiqiXu/Downloads/third year courses/418/computer-graphics-bounding-volume-hierarchy/build_release

**Comment by XQQGOODGIRL** [comment]
make
Scanning dependencies of target glfw
[  2%] Building C object glfw/src/CMakeFiles/glfw.dir/context.c.o
[  5%] Building C object glfw/src/CMakeFiles/glfw.dir/init.c.o
[  7%] Building C object glfw/src/CMakeFiles/glfw.dir/input.c.o
[ 10%] Building C object glfw/src/CMakeFiles/glfw.dir/monitor.c.o
[ 13%] Building C object glfw/src/CMakeFiles/glfw.dir/vulkan.c.o
[ 15%] Building C object glfw/src/CMakeFiles/glfw.dir/window.c.o
[ 18%] Building C object glfw/src/CMakeFiles/glfw.dir/cocoa_init.m.o
[ 21%] Building C object glfw/src/CMakeFiles/glfw.dir/cocoa_joystick.m.o
[ 23%] Building C object glfw/src/CMakeFiles/glfw.dir/cocoa_monitor.m.o
[ 26%] Building C object glfw/src/CMakeFiles/glfw.dir/cocoa_window.m.o
[ 28%] Building C object glfw/src/CMakeFiles/glfw.dir/cocoa_time.c.o
[ 31%] Building C object glfw/src/CMakeFiles/glfw.dir/posix_thread.c.o
[ 34%] Building C object glfw/src/CMakeFiles/glfw.dir/nsgl_context.m.o
[ 36%] Building C object glfw/src/CMakeFiles/glfw.dir/egl_context.c.o
[ 39%] Building C object glfw/src/CMakeFiles/glfw.dir/osmesa_context.c.o
[ 42%] Linking C static library libglfw3.a
libtool: unrecognized option `-c'
libtool: Try `libtool --help' for more information.
make[2]: *** [glfw/src/libglfw3.a] Error 1
make[1]: *** [glfw/src/CMakeFiles/glfw.dir/all] Error 2
make: *** [all] Error 2

**Comment by ACalza** [comment]
What does 'which libtool' return?

**Comment by XQQGOODGIRL** [comment]
/usr/local/bin/libtool

**Comment by ACalza** [comment]
Try re-installing lib tools, brew reinstall libtool, or brew install libtool

**Comment by XQQGOODGIRL** [comment]
I have tried them before not working, or do I have to remove the original one first?

**Comment by ACalza** [comment]
/usr/bin/libtool should be the path of where lib tools was installed via Xcode. If that exists (which it should), you should add that into the path, and remove "/usr/local/bin/libtool" from the path. Try that.

**Comment by dilevin** [comment]
Please upload your make file

**Comment by XQQGOODGIRL** [comment]
[Makefile.txt](https://github.com/dilevin/computer-graphics-bounding-volume-hierarchy/files/2823975/Makefile.txt)

**Comment by rin-23** [comment]
Can you check that /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool
exists?
