### ISSUE TITLE
Triangle Triangle intersection algorithm

### ISSUE THREAD

**Issue by charlesvong** [dilevin/computer-graphics-bounding-volume-hierarchy#32]
So I’ve been trying different algorithms for this function, and so far each of them has given varying results (I.e one algorithm I had less collisions but both brute force and tree collision had the same amount of hits, another algorithm I had more overall collisions but different amount of hits between brute force and tree)

Is it ok if our results just had it so that the brute force and tree collisions are consistent with each other? Without a reference solution I’m not even sure what the correct amount of collisions is and I’ve already confirmed that my intersecting pairs algorithm is working properly.

**Comment by chl9797** [comment]
Yes, that's fine.
