### ISSUE TITLE
Methods to check the correctness of triangle_triangle_intersection

### ISSUE THREAD

**Issue by triangleCZH** [dilevin/computer-graphics-bounding-volume-hierarchy#33]
Although the provided 3 cpp files can validate most the programs by comparing brute force and tree search, there are still two files that cannot be validated:
ray_intersect_triangle.cpp
triangle_triangle_intersection.cpp
That's because both methods use these files.

Currently, I get no errors, but still uncertain about these two files.
May I know if there a way also to validate the above two programs?

**Comment by chl9797** [comment]
We'll treat "triangle_triangle_intersection.cpp" as a bonus task when we do the grading. So you don't need to worry much about this. :)
"ray_intersect_triangle.cpp" is from the previous assignment. Try to make sure that your ray casting works correctly.

**Comment by triangleCZH** [comment]
@chl9797  Thank you for your reply. Since I can see the "bob" and the weird mouse using the viewer, I think my ray_triangle_intersection works correctly.
