### ISSUE TITLE
Ray-box intersection

### ISSUE THREAD

**Issue by cuilantao** [dilevin/computer-graphics-bounding-volume-hierarchy#35]
How should we deal with negative t_values, for example, suppose the box is to the left of our ray.origin, and our ray is shooting upper right, in this case, t_y_min and t_y_max would both be negative values.

**Comment by chl9797** [comment]
t_values is bounded by [min_t,max_t] in this assignment. Since min_t is set to 0, you need to discard t_values that are less than min_t (or negative here).
