### ISSUE TITLE
Performance Penalisation

### ISSUE THREAD

**Issue by DragonMural** [dilevin/computer-graphics-bounding-volume-hierarchy#38]
When I run ./distances 100000 10000 on my release mode,  I generate the correct solution. However my performance is about 200x slower.  This is what I have :

![Screenshot from 2020-02-04 18-35-08](https://user-images.githubusercontent.com/18388850/73797103-16f72080-477d-11ea-9b26-fd26e3bc67cc.png)

This is what we're supposed to get : 
![Screenshot from 2020-02-04 18-36-43](https://user-images.githubusercontent.com/18388850/73797182-532a8100-477d-11ea-9f6a-88c18acc569b.png)

Will we be penalised for large discrepancies in performance?

**Comment by dilevin** [comment]
Your code must demonstrate an asymptotic performance benefit relative to brute force. Performance deficit is almost certainly a sign of a bug somewhere.

**Comment by DragonMural** [comment]
I figured out my issue. When you use a priority queue, make sure the queue is choosing the correct element to process next. My code was functionally correct because I eventually got to the answer but it was slow because it looked at the worst possible elements
