### ISSUE TITLE
use of undefined type error - Eigen

### ISSUE THREAD

**Issue by NPTP** [dilevin/computer-graphics-bounding-volume-hierarchy#40]
Hi,

On Windows here.

I'm using almost the exact same code I used in a previous assignment for ray-triangle intersection (ray_intersect_triangle.cpp), but for some reason, I get an error when trying to do a matrix solve. The following line of code:

`Eigen::Vector3d x = A_matrix.colPivHouseholderQr().solve(B_vector);`

is referenced when VS Studio 2019 gives me this build error:
`use of undefined type 'Eigen::ColPivHouseholderQR<Eigen::Matrix<double,3,3,0,3,3>>`

(note: I get a similar error trying to build on the CDF linux machines)

What's strange is that getting rid of this line and debugging around it shows it looks like things should work, but it just doesn't... and the whole ray_intersect_triangle() function is basically exactly the same code I used in A2 & A3 (which ran on Windows & Linux fine), the only difference is translating the row vectors into column vectors and adding a check to include max_t.

Any ideas what's going on? Thanks!

**Comment by chl9797** [comment]
Could you try including the Eigen QR module using
`#include <Eigen/QR>` 

Remember to do this in your cpp file.

**Comment by NPTP** [comment]
That worked!
I didn't see <Eigen/QR> included anywhere in my .cpp or attached .h files in the last assignment where I used the same function, so I thought that function must be part of <Eigen/Core>. I guess I must have missed its inclusion somehow, through several layers of headers or something? In any case, thank you!
