### ISSUE TITLE
Is there an ideal way to decide where objects on the border of a bounding box split go?

### ISSUE THREAD

**Issue by NPTP** [dilevin/computer-graphics-bounding-volume-hierarchy#45]
Right now I split the parent box along the longest axis and put an object in one side or the other if it fits completely inside of those left/right splits. For objects on the border, I arbitrarily put any object whose bounding box's min_corner is in the left side into the left split, and the rest into the right. Is there a better (but still simple) heuristic to encourage tighter/smaller bounding boxes around groups of objects? Thanks!

**Comment by chl9797** [comment]
You can decide which side to put the objects by the bounding box's center.

**Comment by NPTP** [comment]
Thanks!
