### ISSUE TITLE
Viewer error?

### ISSUE THREAD

**Issue by ginkxo** [dilevin/computer-graphics-bounding-volume-hierarchy#51]
<img width="712" alt="viewer_error" src="https://user-images.githubusercontent.com/21148289/74000876-97618100-4937-11ea-869c-e5e07aaa369f.png">

(running this on CDF).
does anyone know why this might be happening? it occurs right after trying to check the ray hit comparisons.

**Comment by kyokeunpark** [comment]
are you running it through SSH? You can either X11 forward (which I'm not sure if you even can...) or you'd have to try it in person.
