### ISSUE TITLE
Brute force triangle intersect quick question

### ISSUE THREAD

**Issue by NPTP** [dilevin/computer-graphics-bounding-volume-hierarchy#56]
Hi,

I'm debugging and just want to be sure that the brute force algorithm that my tree-based algorithm is being compared against is returning the right things to be compared against!

In `ray_intersect_triangle_mesh_brute_force.cpp`, we have `hit_f` which is the "index into F of triangle that was hit". Should `hit_f` be the index of the ROW of F, or should it be a more literal index (e.g. `row * 3`) ?

Thanks!

**Comment by chl9797** [comment]
The index of the row of F.

**Comment by NPTP** [comment]
Thank you!
