### ISSUE TITLE
I am getting an error on include file for igl 

### ISSUE THREAD

**Issue by ShuvamDas123** [dilevin/computer-graphics-bounding-volume-hierarchy#66]
glad.h is not found.

Can i ignore this error or is it important for the assignment?

**Comment by Zhecheng-Wang** [comment]
I think this is coming from CMake -- you won't be able to build the code with a CMake error.
Did you clone the project with --recursive flag?
If so, try to search the error + your OS online. For Linux, it is easy to fix by installing some packages from package managers.

**Comment by ShuvamDas123** [comment]
Hi I think when I do `cmake `it seems to be cloned. I am doing it right now and I think that works not sure. It just showed glad is cloned when doing `cmake`.

The earlier error was coming from vscode ide problems

**Comment by ShuvamDas123** [comment]
I think it works so closing the issue
