### ISSUE TITLE
How to convert "this" pointer to shared_ptr

### ISSUE THREAD

**Issue by MstrPikachu** [dilevin/computer-graphics-bounding-volume-hierarchy#75]
In `AABBTree_ray_intersect` we want to push tree nodes into the queue. The assignment uses `shared_ptr` a lot so I used that in the queue as well. However, I can't figure out how to push the current object instance into the queue. `make_shared` calls the object constructor but I don't want to make another object. If I just try to push `this`, C++ will complain that it cannot find a matching call to push.

**Comment by MstrPikachu** [comment]
It seems like for this to work you need to edit the .h file.
https://stackoverflow.com/questions/11711034/stdshared-ptr-of-this

**Comment by Zhecheng-Wang** [comment]
Hint: BFS will work with queues, and DFS can work with recursion. Both can do tree traversal.

**Comment by MstrPikachu** [comment]
The first step of the pseudocode is to add the root node to the queue. Without this you end up duplicating a lot of code and it becomes a mess. If there is a way to push the root node into the queue by converting it to `shared_ptr` please let me know.

**Comment by Zhecheng-Wang** [comment]
I think you are referring to [Distance queries](https://github.com/dilevin/computer-graphics-bounding-volume-hierarchy#distance-queries), it is for point-AABB distance queries.

**Comment by MstrPikachu** [comment]
Yes, that's exactly what I'm referring too. I just want to know how to write the 3rd line in C++. Because I have a queue of `shared_ptr`, if I simply do `q.push(this)` the compiler will complain. 


```
// initialize a queue prioritized by minimum distance
d_r ← distance to root's box
Q.insert(d_r, root)
```

**Comment by Zhecheng-Wang** [comment]
For point-AABB distance, [the root is passed in](https://github.com/dilevin/computer-graphics-bounding-volume-hierarchy/blob/183f951e452f9521e6fe1bf2b7f11e6878327698/src/point_AABBTree_squared_distance.cpp#L6) so you can add root to queue.

Again, that pseudocode is for **point-AABB distance**. While ray-AABB intersection is similar, if you have trouble implementing it in BFS with queues, please try DFS with recursions.

**Comment by MstrPikachu** [comment]
Sorry, I got confused between functions for point and ray. Thanks for letting me know.
