### ISSUE TITLE
Some hint on point_AABBTree_squared_distance?

### ISSUE THREAD

**Issue by leoouyang** [dilevin/computer-graphics-bounding-volume-hierarchy#8]
I am trying to identify whether a node is a leaf using typeid(). My result is correct, but the use_tree takes a long time to run with build_type = release(2 sec for brute force, 140 sec for use tree). Is there any hint on a better way to do it?

**Comment by dilevin** [comment]
You can use the fact that non-AABB objects don't return a descendent for their ray intersection calls.

**Comment by leoouyang** [comment]
Sorry, I am still confused. Are we suppose to use ray_intersect in point_AABBTree_squared_distance? We don't have a ray for this function. If the ray doesn't hit anything in the AABB Tree, the descendant would also be untouched. Also, I think its time complexity is too expansive for this checking purpose? Thanks.

**Comment by dilevin** [comment]
Sorry I was confused. I thought you were asking about ray intersection.

**Comment by leoouyang** [comment]
So for point_AABBTree_squared_distance, is there any hint on how should we do it? The only workaround I can think of right now is kind of a hack. The workaround is giving each object an AABB tree wrapper. So for each leaf, instead of the actual object, I create a new AABB Tree node which only contains one object, and use num_leaves to identify those wrappers.

**Comment by rin-23** [comment]
Thats one way to do it. Its not wrong.

**Comment by leoouyang** [comment]
But that increase the size of the tree by about 1/3

**Comment by rin-23** [comment]
you canst objet to AABB tree like this  
std::shared_ptr<AABBTree> subtree = std::dynamic_pointer_cast<AABBTree>(object);

**Comment by leoouyang** [comment]
So I have tried my hack and the dynamic_pointer_cast. It is still very slow for some reason. I think it may be some other reason. I will try to find out. BTW, I am testing with Bash on Ubuntu on Windows. Maybe a compatibility problem?

**Comment by rin-23** [comment]
I dont think OS environment matters

**Comment by leoouyang** [comment]
Ok, I find it out. That was such a stupid mistake. So when finding the longest axis and calculate the split value for AABB tree, I make a minor mistake. So my split_val was wrong all the time and my AABB tree is very skewed, I believe. Thank you for your help.

**Comment by rin-23** [comment]
great!
