### ISSUE TITLE
AABBTree::ray_intersect use tree longer than brute force

### ISSUE THREAD

**Issue by buencons** [dilevin/computer-graphics-bounding-volume-hierarchy#9]
It looks like my use tree time is longer than the brute force for AABBTree::ray_intersect

  | Method      | Time in seconds |
  |:------------|----------------:|
  | brute force |   0.40938425064 |
  | build tree  |   0.00643968582 |
  | use tree    |   0.61487460136 |

Are there any reasons for why this could be happening? My AABBTree ray intersect algorithm is the same as what was given in the textbook.
Thanks.

**Comment by rin-23** [comment]
Yes make sure you only traverse children is their parent passed the intersection test.

**Comment by buencons** [comment]
My implementation of ray_intersect_box was incorrect and was always returning true. This made my algorithm traverse the whole tree for each intersection test.
