### ISSUE TITLE
Segfault in intersections.cpp for the command './intersections ../data/cheburashka.obj ../data/knight.obj'

### ISSUE THREAD

**Issue by burneracc0112** [dilevin/computer-graphics-bounding-volume-hierarchy#94]
However, `./intersections ../data/knight.obj ../data/cheburashka.obj works`

The code was segfaulting so I enabled assert statements and tracked down the segfault to the narrow phase in intersections.cpp

The failure is because of -
```
/csc317/csc317_bvh/include/Eigen/src/Core/DenseCoeffsBase.h:364: Eigen::DenseCoeffsBase<Derived, 1>::Scalar& Eigen::DenseCoeffsBase<Derived, 1>::operator()(Eigen::Index, Eigen::Index) [with Derived = Eigen::Matrix<int, -1, -1>; Eigen::DenseCoeffsBase<Derived, 1>::Scalar = int; Eigen::Index = long int]: Assertion `row >= 0 && row < rows() && col >= 0 && col < cols()' failed.
```

However, I changed the `static_pointer_cast` to `dynamic_pointer_cast` (line 90 of intersections.cpp) and, using asserts, I verified that the pointers triangleA, and triangleB are not nullptr, which means they were succesfully casted to MeshTriangle.

I don't understand why this issue is happening if the pointers point to valid triangles.

**Comment by Zhecheng-Wang** [comment]
It looks like this might be an indexing error. Can you post the call stack? Please note that the data could be represented as a RowVector instead of a Vector, so it would be great if you could take extra care with how the indexing is handled.

**Comment by burneracc0112** [comment]
This is the stacktrace I am getting
```
Error: signal 11:
./intersections(_Z7handleri+0x30)[0x5579783c6bc0]
/lib/x86_64-linux-gnu/libc.so.6(+0x42520)[0x7f49d4454520]
./intersections(main+0xa36)[0x5579783c5ee6]
/lib/x86_64-linux-gnu/libc.so.6(+0x29d90)[0x7f49d443bd90]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80)[0x7f49d443be40]
./intersections(_start+0x25)[0x5579783c6ac5]
```

This was the stack trace generated by gdb, which also showss the error being in line 97 of intersections.cpp
<img width="1512" alt="Screenshot 2024-10-04 at 1 13 23 PM" src="https://github.com/user-attachments/assets/63690e95-480e-4f98-a341-0b59ef77bf74">

The error seems to be happening when creating row vectors using the triangle data. It never manages to enter triangle_triangle_intersection and is failing within the starter code itself.

However, since I verified using `dynamic_pointer_cast` and `assert` that the pointers `triangleA` and `triangleB` are not nullptr, the triangles must be valid triangles, in which case I don't see why there is a failure specifically for this input. 

Especially since `./intersections ../data/knight.obj ../data/cheburashka.obj` is working but `./intersections ../data/cheburashka.obj ../data/knight.obj` is not.

**Comment by burneracc0112** [comment]
The issue turned out to be that the triangles of trees were geting pushed out of order sometimes
