### ISSUE TITLE
time to run intersect

### ISSUE THREAD

**Issue by Rishit-dagli** [dilevin/computer-graphics-bounding-volume-hierarchy#97]
I have been trying to run intersection:

```
./intersections ../data/knight.obj ../data/cheburashka.obj

# Triangle Mesh Intersection Detection
  |VA| 2002
  |FA| 4000

  |VB| 6669
  |FB| 13334

  | Method      | Time in seconds |
  |:------------|----------------:|
  | brute force |   7.59933805466 |
  | build trees |   0.00876474380 |
```

these meshes are bigger relative to the previous meshes. however, it has been a few minutes since this has been running and i was wondering how long is finding intersecting pairs expected to take?

**Comment by Zhecheng-Wang** [comment]
Did you build in release?

**Comment by Rishit-dagli** [comment]
yes

and i just fixed it
